netdev-offload-dpdk: Fix IPv6 rewrite cast-align warning
Compile with -Werror and -Wcast-align:

lib/netdev-offload-dpdk.c:578:30: error: cast increases required alignment
    of target type [-Werror=cast-align]
  578 |    ipv6_format_addr((struct in6_addr *) &set_ipv6->ipv6_addr, s);
      |                     ^

Fix it.

Change-Id: I39bdd0fd84038334367ea702398e16d1f7cb2fdf
Fixes: b6207b1d2711 ("netdev-offload-dpdk: Support offload of set IPv6 actions.")
Signed-off-by: Eli Britstein <elibr@nvidia.com>