netdev-offload-dpdk: Fix cast-align warnings in find_raw_encap_spec()
The function parses a raw header to layer headers and introduced the
below warnings. Fix them.

lib/netdev-offload-dpdk.c: In function 'find_raw_encap_spec':
lib/netdev-offload-dpdk.c:5427:11: error: cast increases required alignment of target type [-Werror=cast-align]
 5427 |     eth = (struct eth_header *) raw_encap_data->conf.data;
      |           ^
lib/netdev-offload-dpdk.c:5436:16: error: cast increases required alignment of target type [-Werror=cast-align]
 5436 |         vlan = (struct vlan_header *) next_hdr;
      |                ^
lib/netdev-offload-dpdk.c:5442:16: error: cast increases required alignment of target type [-Werror=cast-align]
 5442 |         ipv4 = (struct ip_header *) next_hdr;
      |                ^
lib/netdev-offload-dpdk.c:5453:16: error: cast increases required alignment of target type [-Werror=cast-align]
 5453 |         ipv6 = (struct ovs_16aligned_ip6_hdr *) next_hdr;
      |                ^

Issue: OVS-3356968
Fixes: 9860c1b12a21 ("netdev-offload-dpdk: Support raw_encap header rewrite")
Signed-off-by: Eli Britstein <elibr@nvidia.com>