dpif-netdev: Fix unused variable/parameter w/o dpdk
If compiled withtout dpdk support, there is no
ALLOW_EXPERIMENTAL_SUPPORT defined. As such, there are unused
variable/parameter warnings:

lib/dpif-netdev.c:10937:28: error: unused variable ‘sflow_attr’ [-Werror=unused-variable]
     struct dpif_sflow_attr sflow_attr = {
                            ^~~~~~~~~~
lib/dpif-netdev.c:10933:28: error: unused parameter ‘skip_actions’ [-Werror=unused-parameter]
                   uint8_t *skip_actions)
                   ~~~~~~~~~^~~~~~~~~~~~

Fix it by adding OVS_UNUSED attribute to them.

Issue: 3104800
Change-Id: Iaad346ca87b98900387c33ba31d263c97e883218
Signed-off-by: Eli Britstein <elibr@nvidia.com>