dpctl: Fix compilation warning
Add missing include of ctype.h

lib/dpctl.c: In function ‘dpctl_validate_sort_list’:
lib/dpctl.c:1139:15: warning: implicit declaration of function ‘islower’ [-Wimplicit-function-declaration]
1139 |         if (!(islower(s[i]) || isdigit(s[i]) ||
     |               ^~~~~~~
lib/dpctl.c:55:1: note: include ‘<ctype.h>’ or provide a declaration of ‘islower’
   54 | #include "openvswitch/ofp-port.h"
  +++ |+#include <ctype.h>
   55 |
lib/dpctl.c:1139:32: warning: implicit declaration of function ‘isdigit’ [-Wimplicit-function-declaration]
1139 |         if (!(islower(s[i]) || isdigit(s[i]) ||
     |                                ^~~~~~~

Change-Id: If60f2bc043ccc9e7b1dfbad77fb97cde1336e10c
Fixes: 1b1e73e0e84c ("dpctl: Add sort option to dump-flows")
Signed-off-by: Roi Dayan <roid@nvidia.com>