netdev-offload-dpdk: Fix vxlan vni cast-align warnings
Compiling with -Werror and -Wcast-align has errors like:

lib/netdev-offload-dpdk.c: In function 'dump_flow_pattern':
lib/netdev-offload-dpdk.c:385:38: error: cast increases required alignment
    of target type [-Werror=cast-align]
  385 |    ntohl(*(ovs_be32 *) vxlan_spec->vni) >> 8,
      |           ^

Fix them.

Change-Id: I03bbdd45ae37b763f1e006ef8691c64dd4bfb3bf
Reported-by: Harry Van Haaren <harry.van.haaren@intel.com>
Fixes: 4e432d6f8128 ("netdev-offload-dpdk: Support tnl/push using vxlan encap attribute.")
Fixes: e098c2f966cb ("netdev-dpdk-offload: Add vxlan pattern matching function.")
Signed-off-by: Eli Britstein <elibr@nvidia.com>