ovs-ofctl: Fix 'usable_protocols' may be used uninitialized
With --enable-Werror and --with-dpdk=no:

../utilities/ovs-ofctl.c: In function 'ofctl_group_mod_file':
../utilities/ovs-ofctl.c:3107:16: error: 'usable_protocols' may be used uninitialized in this function [-Werror=maybe-uninitialized]
 3107 |     protocol = open_vconn_for_flow_mod(remote, &vconn, usable_protocols);
      |                ^
../utilities/ovs-ofctl.c:3124:27: note: 'usable_protocols' was declared here
 3124 |     enum ofputil_protocol usable_protocols;
      |                           ^

Change-Id: If63dca1dee84ea675af2663d3080ea58513be144
Fixes: 69185eb25acb ("ovs-ofctl: Only allow usable protocols for group commands")
Signed-off-by: Eli Britstein <elibr@nvidia.com>