dp-packet: Fix dp-packet may be used initialized
With --enable-Werror and --with-dpdk=no:

In function 'dp_packet_reset_offload',
    inlined from 'dp_packet_init__' at ../lib/dp-packet.c:35:5,
    inlined from 'dp_packet_use__' at ../lib/dp-packet.c:50:5,
    inlined from 'dp_packet_use' at ../lib/dp-packet.c:60:5,
    inlined from 'dp_packet_init' at ../lib/dp-packet.c:126:5,
    inlined from 'dp_packet_new' at ../lib/dp-packet.c:154:5:
../lib/dp-packet.h:944:32: error: 'MEM[(uint32_t *)p_14 + 16B]' may be used uninitialized [-Werror=maybe-uninitialized]
  944 |     *dp_packet_ol_flags_ptr(p) &= ~DP_PACKET_OL_SUPPORTED_MASK;
      |                                ^

Fixes: a47e2db209e4 ("dp-packet: Refactor offloading API.")
Change-Id: Ie129e957f879f0b0eb929ed924c43b6f1711ebaf
Signed-off-by: Eli Britstein <elibr@nvidia.com>