ofproto: Fix 'reply.type' may be used uninitialized
../ofproto/ofproto.c: In function 'handle_openflow':
../lib/ofp-bundle.c:195:15: error: 'reply.type' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  195 |     m->type = htons(msg->type);
      |               ^
../ofproto/ofproto.c:8460:36: note: 'reply.type' was declared here
 8460 |     struct ofputil_bundle_ctrl_msg reply;
      |                                    ^

Fixes: 777af88d50b8 ("Add basic implementation for OpenFlow 1.4 bundles")
Change-Id: I51ad69d56b15b508cafcdda3b051af2db16b3d7f
Signed-off-by: Eli Britstein <elibr@nvidia.com>