ovsdb: Fix 'table' may be used uninitialized
With --enable-Werror and --with-dpdk=no:

../ovsdb/ovsdb.c: In function 'ovsdb_schema_from_json':
../ovsdb/ovsdb.c:246:9: error: 'table' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  246 |         shash_add(&schema->tables, table->name, table);
      |         ^
../ovsdb/ovsdb.c:230:36: note: 'table' was declared here
  230 |         struct ovsdb_table_schema *table;
      |                                    ^

Change-Id: I4e98d4752bc3c75259befda7b48fbf97bca0149f
Fixes: f85f8ebbfac9 ("Initial implementation of OVSDB.")
Signed-off-by: Eli Britstein <elibr@nvidia.com>