netdev-offload-dpdk: Fix parse_geneve_match() cast align warnings
lib/netdev-offload-dpdk.c: In function ‘parse_geneve_match’:
lib/netdev-offload-dpdk.c:3411:24: error: cast increases required alignment of target type [-Werror=cast-align]
3411 |     put_unaligned_be32((ovs_be32 *)gnv_spec->vni,
     |                        ^
lib/netdev-offload-dpdk.c:3413:24: error: cast increases required alignment of target type [-Werror=cast-align]
3413 |     put_unaligned_be32((ovs_be32 *)gnv_mask->vni,
     |      ))

Issue: OVS-3263712
Fixes: 4f131d5894 ("netdev-offload-dpdk: Add geneve header pattern match")
Signed-off-by: Salem Sol <salems@nvidia.com>