dpctl: Fix zone/limit may be used uninitialized
With --enable-Werror and --with-dpdk=no:

../lib/dpctl.c: In function 'dpctl_ct_set_limits':
../lib/ct-dpif.c:698:22: error: 'zone' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  698 |     zone_limit->zone = zone;
      |                      ^
../lib/dpctl.c:2139:18: note: 'zone' was declared here
 2139 |         uint16_t zone;
      |                  ^

../lib/ct-dpif.c:699:23: error: 'limit' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  699 |     zone_limit->limit = limit;
      |                       ^
../lib/dpctl.c:2140:18: note: 'limit' was declared here
 2140 |         uint32_t limit;
      |                  ^

Change-Id: I305a94a2cc522dff6552bfb534115b79310b031b
Fixes: 4eeec031d4c4 ("dpctl: Implement dpctl commands for conntrack per zone limit")
Signed-off-by: Eli Britstein <elibr@nvidia.com>