netdev-offload-dpdk: Fix vlan push cast-align warning
lib/netdev-offload-dpdk.c: In function ‘parse_flow_actions’:
lib/netdev-offload-dpdk.c:5396:19: error: cast increases required alignment of target type [-Werror=cast-align]
 5396 |             veh = (struct vlan_eth_header *) raw_encap_data->conf.data;
      |                   ^

Issue: OVS-3263712
Fixes: 17c3c122 ("netdev-offload-dpdk: Support VLAN push to raw_encap")
Signed-off-by: Salem Sol <salems@nvidia.com>