packets: Fix memset writing 17 bytes into a region of size 0
In function 'memset',
    inlined from 'pkt_metadata_init' at ../../lib/packets.h:173:5,
    inlined from 'ofctl_parse_pcap' at ../../utilities/ovs-ofctl.c:4617:13:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:59:10: error:
    '__builtin_memset' writing 17 bytes into a region of size 0 overflows the
    destination
    [https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wstringop-overflow=-Werror=stringop-overflow=]
   59 |   return __builtin___memset_chk (__dest, __ch, __len,
      |          ^
Zero the fields explicitly instead of using memset.

OVS-issue: 3282529
Signed-off-by: Eli Britstein <elibr@nvidia.com>