ovs-doca: Fix clang mutex 'once_enable.mutex'
lib/ovs-doca.c:303:1: error: mutex 'once_enable.mutex' is not held on
 every path through here [-Werror,-Wthread-safety-analysis]

Fixes: c609b72d22f3 ("vswitchd: Add 'doca-init' flag")
Signed-off-by: Eli Britstein <elibr@nvidia.com>