Revert "netdev-dpdk: Pass struct netdev instead of netdev_dpdk in dpdk_eth_dev_init()"
dpdk_eth_dev_init() was changed to get netdev instead of dev, but kept
OVS_REQUIRES(dev->mutex).

clang detects this error:
lib/netdev-dpdk.c:1232:18: error: use of undeclared identifier 'dev'

Revert this change, and get netdev from dev->up.

This reverts commit 1a535c97c6890a5b67972708559997d4d924634b.