netdev-dpdk-vdpa: Fix netdev_dpdk_vdpa_parse_pkt() cast align warning
lib/netdev-dpdk-vdpa.c: In function ‘netdev_dpdk_vdpa_parse_pkt’:
lib/netdev-dpdk-vdpa.c:530:19: error: cast increases required alignment of target type [-Werror=cast-align]
  530 |             tcp = (const struct tcp_header *)((char *)ipv4 + l3_len);
      |                   ^

Issue: OVS-3263712
Fixes: 58537f3b2c ("netdev-dpdk-vdpa: Introduce dpdkvdpa netdev")
Signed-off-by: Salem Sol <salems@nvidia.com>