ofp-port: Fix 'strnlen' specified bound may exceed source size
With --enable-Werror and --with-dpdk=no:

In function 'ovs_strlcpy',
    inlined from 'ovs_strlcpy' at ../lib/util.c:377:1,
    inlined from 'ofputil_port_to_string' at ../lib/ofp-port.c:273:9,
    inlined from 'ofputil_port_from_string.part.0' at ../lib/ofp-port.c:170:13:
../lib/util.c:380:22: error: 'strnlen' specified bound 15 may exceed source size 11 [-Werror=stringop-overread]
  380 |         size_t len = strnlen(src, size - 1);
      |                      ^

Change-Id: I17747b8d87f13d2d1026922c7cd3048127a8c74f
Fixes: 28b114322856 ("ofp-util: New function ofputil_port_to_string().")
Signed-off-by: Eli Britstein <elibr@nvidia.com>